export enum ERROR_MESSAGES {
  INCORRECT_EMAIL_OR_PASSWORD = "INCORRECT_EMAIL_OR_PASSWORD",
  NOT_LOGGED_IN = "NOT_LOGGED_IN",
  SERVER_ERROR = "SERVER_ERROR",
  NOT_IN_RECORDS_PAGE = "NOT_IN_RECORDS_PAGE",
}

export enum PAGES_NAMES {
  HOME = "HOME_PAGE",
  RECORDS = "RECORDS_PAGE",
}
